#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: Copyright (c) 2026 Daniel Langford

import argparse
import datetime
import html
import json
import pathlib
import ssl
import sys
import urllib.request


ROOT = pathlib.Path(__file__).resolve().parents[1]
SNAPSHOT = ROOT / "rules" / "buttonweavers-skills.json"
REFERENCE = ROOT / "docs" / "skill-rules.md"
LOCAL_SNAPSHOT = ROOT / "rules" / "buttonweavers-skills.local.json"
LOCAL_REFERENCE = ROOT / "docs" / "skill-rules.local.md"
SOURCE_PAGE = "https://www.buttonweavers.com/ui/skills.html"
API_ENDPOINT = "https://www.buttonweavers.com/api/responder"
SYSTEM_CA_FILE = pathlib.Path("/etc/ssl/cert.pem")


def fetch(api_type):
    request = urllib.request.Request(
        API_ENDPOINT,
        data=json.dumps({"type": api_type}).encode("utf-8"),
        headers={"Content-Type": "application/x-www-form-urlencoded"},
        method="POST",
    )
    context = ssl.create_default_context()
    if SYSTEM_CA_FILE.exists():
        context.load_verify_locations(cafile=SYSTEM_CA_FILE)
    with urllib.request.urlopen(request, timeout=30, context=context) as response:
        result = json.load(response)
    if result.get("status") != "ok" or not isinstance(result.get("data"), dict):
        raise RuntimeError(result.get("message") or f"{api_type} returned invalid data")
    return result["data"]


def load_snapshot():
    with SNAPSHOT.open(encoding="utf-8") as source:
        snapshot = json.load(source)
    required = {
        "schema_version", "source", "fetched_at", "api_requests", "dieSkills", "dieTypes"
    }
    missing = required - snapshot.keys()
    if missing:
        raise ValueError(f"snapshot is missing: {', '.join(sorted(missing))}")
    if not snapshot["dieSkills"] or not snapshot["dieTypes"]:
        raise ValueError("snapshot contains no skills or die types")
    return snapshot


def normalize(snapshot):
    def names(items):
        if not isinstance(items, dict) or not items:
            raise ValueError("rules data must be a non-empty object")
        result = {}
        for code, info in items.items():
            if not isinstance(info, dict) or not isinstance(info.get("name"), str):
                raise ValueError(f"rules entry {code!r} has no name")
            result[code] = {"name": info["name"]}
        return result

    return {
        "schema_version": 2,
        "description": "Button Weavers identifiers for development reference; not used at runtime.",
        "source": snapshot["source"],
        "fetched_at": snapshot["fetched_at"],
        "api_requests": snapshot["api_requests"],
        "dieSkills": names(snapshot["dieSkills"]),
        "dieTypes": names(snapshot["dieTypes"]),
    }


def code_sort(item):
    code = item[0]
    return len(code), code.lower(), code


def text(value):
    return html.escape(str(value), quote=False).replace("\n", " ")


def render(snapshot):
    lines = [
        "<!--",
        "SPDX-License-" + "Identifier: MIT",
        "SPDX-FileCopyrightText: Copyright (c) 2026 Daniel Langford",
        "This file is generated by scripts/update_buttonweavers_skills.py.",
        "-->",
        "",
        "# Button Weavers Skill Rules",
        "",
        f"Source: [{snapshot['source']}]({snapshot['source']})",
        f"Snapshot fetched: `{snapshot['fetched_at']}`",
        "Implementation status: [skill-status.md](skill-status.md)",
        "",
        "Do not edit this file directly. Run `python3 scripts/update_buttonweavers_skills.py` to refresh it.",
        "",
        "## Skills",
        "",
    ]
    for code, info in sorted(snapshot["dieSkills"].items(), key=code_sort):
        lines.extend([
            f"### {text(info['name'])} (<code>{text(code)}</code>)",
            "",
            f"Rule text: [Button Weavers]({snapshot['source']})",
            "",
        ])

    lines.extend(["## Die Types", ""])
    for code, info in sorted(snapshot["dieTypes"].items(), key=code_sort):
        lines.extend([
            f"### {text(info['name'])} (<code>{text(code)}</code>)",
            "",
            f"Rule text: [Button Weavers]({snapshot['source']})",
            "",
        ])
    return "\n".join(lines)


def render_local(snapshot):
    lines = [
        "# Button Weavers Skill Rules (Local Cache)",
        "",
        f"Source: [{snapshot['source']}]({snapshot['source']})",
        f"Fetched: `{snapshot['fetched_at']}`",
        "This unlicensed upstream text is for local development reference and is not distributed with BMAI.",
        "",
        "## Skills",
        "",
    ]
    for code, info in sorted(snapshot["dieSkills"].items(), key=code_sort):
        lines.extend([f"### {text(info['name'])} (<code>{text(code)}</code>)", "", text(info["description"]), ""])
        interactions = info.get("interacts") or {}
        for name, description in sorted(interactions.items()):
            lines.append(f"- **{text(name)}:** {text(description)}")
        if interactions:
            lines.append("")

    lines.extend(["## Die Types", ""])
    for code, info in sorted(snapshot["dieTypes"].items(), key=code_sort):
        lines.extend([f"### {text(info['name'])} (<code>{text(code)}</code>)", "", text(info["description"]), ""])
    return "\n".join(lines)


def write_outputs(snapshot, reference, snapshot_path=SNAPSHOT, reference_path=REFERENCE, replace_file=None):
    if replace_file is None:
        replace_file = lambda source, destination: source.replace(destination)
    snapshot_tmp = snapshot_path.with_suffix(snapshot_path.suffix + ".tmp")
    reference_tmp = reference_path.with_suffix(reference_path.suffix + ".tmp")
    snapshot_tmp.write_text(json.dumps(snapshot, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    reference_tmp.write_text(reference, encoding="utf-8")
    previous_snapshot = snapshot_path.read_bytes() if snapshot_path.exists() else None
    replace_file(snapshot_tmp, snapshot_path)
    try:
        replace_file(reference_tmp, reference_path)
    except Exception:
        if previous_snapshot is None:
            snapshot_path.unlink(missing_ok=True)
        else:
            snapshot_path.write_bytes(previous_snapshot)
        raise
    finally:
        snapshot_tmp.unlink(missing_ok=True)
        reference_tmp.unlink(missing_ok=True)


def main():
    parser = argparse.ArgumentParser(description="Refresh the Button Weavers rules snapshot and reference.")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--offline", action="store_true", help="render Markdown from the checked-in snapshot")
    mode.add_argument("--check", action="store_true", help="validate the snapshot and generated Markdown")
    args = parser.parse_args()

    if args.check:
        snapshot = load_snapshot()
        expected_snapshot = json.dumps(snapshot, indent=2, sort_keys=True) + "\n"
        if SNAPSHOT.read_text(encoding="utf-8") != expected_snapshot:
            print(f"{SNAPSHOT.relative_to(ROOT)} is not normalized", file=sys.stderr)
            return 1
        expected = render(snapshot)
        actual = REFERENCE.read_text(encoding="utf-8") if REFERENCE.exists() else ""
        if actual != expected:
            print(f"{REFERENCE.relative_to(ROOT)} is stale", file=sys.stderr)
            return 1
        print(f"validated {len(snapshot['dieSkills'])} skills and {len(snapshot['dieTypes'])} die types")
        return 0

    if args.offline:
        snapshot = normalize(load_snapshot())
    else:
        upstream = {
            "schema_version": 1,
            "description": "Reference rules for humans and development tools; not consumed by BMAI at runtime.",
            "source": SOURCE_PAGE,
            "fetched_at": datetime.datetime.now(datetime.timezone.utc)
            .replace(microsecond=0)
            .isoformat()
            .replace("+00:00", "Z"),
            "api_requests": [
                {"endpoint": API_ENDPOINT, "body": {"type": "loadDieSkillsData"}},
                {"endpoint": API_ENDPOINT, "body": {"type": "loadDieTypesData"}},
            ],
            "dieSkills": fetch("loadDieSkillsData"),
            "dieTypes": fetch("loadDieTypesData"),
        }
        local_reference = render_local(upstream)
        snapshot = normalize(upstream)

    reference = render(snapshot)
    write_outputs(snapshot, reference)
    if not args.offline:
        write_outputs(upstream, local_reference, LOCAL_SNAPSHOT, LOCAL_REFERENCE)
    print(f"wrote {SNAPSHOT.relative_to(ROOT)} and {REFERENCE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
